apiVersion: v1
kind: PersistentVolume
metadata:
  name: k6-persistent-pv
spec:
  capacity:
    #storage: 1Gi
    storage: 50M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
