apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-java-app-pipeline
spec:
  description: | 
    This pipeline builds a java maven project.
  params:
  - name: repo-url
    type: string
    description: The git repo URL to clone from.
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-data
      params:
      - name: url
        value: $(params.repo-url)
      - name: subdirectory
        value: "demo-java-app"
    - name: build
      taskRef:
        name: demo-java-app-build-task
      runAfter:
        - fetch-source
      workspaces:
        - name: shared-data
          workspace: shared-data